### ISSUE TITLE
problem exporting imageCollection to drive

### ISSUE THREAD

**Issue by camile-sothe** [fitoprincipe/geetools-code-editor#10]
Hi Rodrigo,

Thank you for providing these GEE tools!

Im trying to export an image collection from GEE to drive, or cloud storage, using your code (batch).
Im getting this error:

**In users/fitoprincipe/geetools:batch
Line 133: collection.size is not a function**

Do you know how can I solve this? My code below:

```
var collection = ee.ImageCollection('LANDSAT/LC08/C01/T1_SR')
   .filterBounds(studyArea).filterDate('2019-01-01', '2019-12-31')
   .filterMetadata('CLOUD_COVER', 'less_than', 30);
print(collection)

var batch = require('users/fitoprincipe/geetools:batch')
var count = collection.size()
print("Coleccion", count)

// Export the image, specifying scale and region.
 batch.Download.ImageCollection.toDrive({
   image: collection,
   description: 'imageCollection_L8_2019',
   scale: 30,
   region: studyArea,
   fileFormat: 'GeoTIFF',
   formatOptions: {
    cloudOptimized: true
  }
 });
```

**Comment by fitoprincipe** [comment]
Hello @camile-sothe , thank you for using my package =)

The issue is that you are using the same params as the `Export.toDrive` function in the JS API, but this function takes different params: https://github.com/fitoprincipe/geetools-code-editor/wiki/Batch#imagecollectiontodrivecollection-folder-options

let me know

**Comment by camile-sothe** [comment]
I realized that later, thank you! Im trying some ways to automatically run all tasks to export all images without manually click **run**, I found a tutorial gee-monkey but didnt work. Please, let me know if you have any suggestions. Thank you again!
