### ISSUE TITLE
Invalid GeoJSON geometry error when trying to batch download

### ISSUE THREAD

**Issue by sir247** [fitoprincipe/geetools-code-editor#2]
I receive an error when executing the following script:

var batch = require('users/fitoprincipe/geetools:batch')
var col = ee.ImageCollection("LANDSAT/LE07/C01/T1_SR").filterDate("2002-01-01","2002-01-03");
batch.Download.ImageCollection.toDrive(col, "Folder", {scale:30});

Invalid GeoJSON geometry: [[[-73.87879425086899,46.471905677908346],[-70.84547603387989,46.471905677908346],[-70.84547603387989,48.4283626121078],[-73.87879425086899,48.4283626121078],[-73.87879425086899,46.471905677908346]]]

Why is this occurring?

**Comment by fitoprincipe** [comment]
Hi @sir247 , I'll try to fix it as soon as I can. I've been doing some changes to the code and may have beak it. Sorry

**Comment by fitoprincipe** [comment]
Hi @sir247 , can you try it now?

**Comment by jcintasr** [comment]
Hi there @fitoprincipe , I've been trying to use your functions, but I received the same error as @sir247 when downloading an ImageCollection. I hope my experience help you solve it :)

**Comment by fitoprincipe** [comment]
I tried yesterday to solve issue #3 and was working fine :thinking:

**Comment by jcintasr** [comment]
That's odd, 
maybe I am pointing to the wrong version.

To sum up, I have an ImageCollection of 4 years of sentinel-2 images that I subseted and clipped,
then I call to the batch functions to try to download it.

`var batch = require('users/fitoprincipe/geetools:batch') `
`batch.Download.ImageCollection.toAsset(clipped, 'donana', {scale: 10});`

It returns the next error:


Invalid GeoJSON geometry: [[[-6.6709003702302425,36.7402714416414],[-6.0693989053864925,36.7402714416414],[-6.0693989053864925,37.27543039428127],[-6.6709003702302425,37.27543039428127],[-6.6709003702302425,36.7402714416414]]]

Let me know if more information is needed

**Comment by fitoprincipe** [comment]
Oh, so you are not using `toDrive` but `toAsset`, that is different. I haven't upgraded that function yet, sorry.

**Comment by jcintasr** [comment]
Yes, my bad sorry. 
I updated the code and it is working fine now. Thank you! :)
