### ISSUE TITLE
String: Unable to convert object to string.

### ISSUE THREAD

**Issue by eupassarinho** [fitoprincipe/geetools-code-editor#3]
Dears,

I'm have a problem applying the function batch to download an image collection of Sentinel-1 satellite. With this code:

`var roi = ee.FeatureCollection('ft:16UGb-zfZNV_Nc2-YQyWs9tzPZgkeXBeCgi9ke51Q');

//Criando a variável, como coleção, para armazenar as cenas filtradas:
var sentinel1 = ee.ImageCollection('COPERNICUS/S1_GRD')
    .filter(ee.Filter.eq('instrumentMode', 'IW'))
    .filter(ee.Filter.eq('orbitProperties_pass', 'DESCENDING'))
    .filterBounds(roi)
    .filterDate('2019-08-01', '2019-08-31');
    
var S1 = sentinel1.select(['VV', 'VH']);

//Exibindo no Console os produtos encontrados:
print(S1);

//Exibindo no mapa o vetor e as cenas:
Map.centerObject(roi, 7.5)
Map.addLayer(S1,{bands:['VH'], min: -20, max: 5})

//Exportando coleção para o drive:
var batch = require('users/fitoprincipe/geetools:batch')
batch.Download.ImageCollection.toDrive(S1, "S1", {scale: 10, region:roi})`

Result in this error and the images aren't downloaded in google drive:
"**String: Unable to convert object to string.**"

Follows the link to my code in GEE:
https://code.earthengine.google.com/9bab8775a744cb30fa347e2d8a6e6126

Thank you by attention!
My bests regards.

**Comment by fitoprincipe** [comment]
Hi @eupassarinho ,

Thank you. I have fixed now. The issue was that S1 images have a property that is a list, and as I cannot determine the `type` of each value of the properties I cannot make a conditional to format it properly, so this lead to a change in `toDrive` function:

Now, if you are going to use a property as name, you have to specify the property in the options. For example:

``` javascript
batch.Download.ImageCollection.toDrive(S1, "S1", {
    scale: 10,
    region:roi,
    name: '{instrumentMode} {id}',
    properties: ['instrumentMode']
})`
```

**Comment by eupassarinho** [comment]
Hi @fitoprincipe ,

Thank you for your prompt reply. The solution has worked in my script! Only another thing more: when I use the function:

``batch.Download.ImageCollection.toDrive(S1, "S1", {
    scale: 10,
    region:roi,
    name: '{instrumentMode} {id}',
    properties: ['instrumentMode']
})``

The final product is a stack of the bands in each image of the image collection. In my case, the bands are wrote how "band_1" and "band_2". There is any form to indicate the real name of the band? Exporting how "VV" and "VH"?

Thank you very much!

**Comment by fitoprincipe** [comment]
I have recently exported an image to Google Drive, and when I opened it with QGIS I was surprised it kept the band names, something that did not happen before. What software do you use to open the file?

**Comment by eupassarinho** [comment]
I'm using SNAP (Sentinel-1 Toolbox) and appears how band_1 and band_2 to VV and VH bands, but I have opened the images in QGIS and did has worked like you did says: it kepd the band names!
