### ISSUE TITLE
difference from cloudmask in ee

### ISSUE THREAD

**Issue by shikunWu** [fitoprincipe/geetools-code-editor#6]
Hi,Rodrigo
  I want to know the difference between the landsat cloud mask part and the official website of gee, I found that he kept more information. Can you tell me why?
Sorry，I am not very proficient in code.

**Comment by fitoprincipe** [comment]
Hi @shikunWu , can you share a link of the _official website of gee_? just to be sure we are in the same page =) Cheers

**Comment by shikunWu** [comment]
ok he is the link: https://code.earthengine.google.com/e7a62d6ca241f16140363d257268b2dd?noload=1

**Comment by shikunWu** [comment]
hello?
Can you give me some guidance
