### ISSUE TITLE
Regarding geetools (cloud masks)

### ISSUE THREAD

**Issue by FurquanAnwer** [fitoprincipe/geetools-code-editor#8]
Hi,
I am using your **geetool** for **cloud masking** but its not working for **Landsat 8 Collection 2 images.**
Could you please guide me because I need to mask out cloud.
Here is the code ---
var cloud_masks = require('users/fitoprincipe/geetools:cloud_masks');
var landsatSRfunction = cloud_masks.landsatSR;

// The original Image
var L8Image = ee.Image('LANDSAT/LC08/C02/T1_L2/LC08_140046_20200115');

// Apply mask
var masked_image = landsatSRfunction()(L8Image);

// Visualize
var vis = {bands:['SR_B5', 'SR_B7', 'SR_B4'], min:0, max:30000}
Map.addLayer(masked_image, vis, 'Landsat 8 SR masked');
Map.centerObject(masked_image)

**Comment by jess-paige** [comment]
Hey, I am also using this tool and it worked fine a few days ago but since then I think GEE must have deprecated the collection 1 surface reflectance image collections that this tool is designed to use (LANDSAT/LT04/C01/T1_SR, LANDSAT/LT05/C01/T1_SR, LANDSAT/LE07/C01/T1_SR, LANDSAT/LC08/C01/T1_SR). I don't know how easy it would be to change the tool to work with other Landsat collections instead but would love to know if this change is made.

**Comment by fitoprincipe** [comment]
Hi! Thanks for the feedback. I tried to quickly fix it. Let me know if it works. There should be a `landsatSR2` function now to be applied in the new collection.

**Comment by jess-paige** [comment]
Hi @fitoprincipe I think that works do you mind just specifying which image collections that works with now?  using print(mask.help['landsatSR2']) only returns "undefined". Otherwise thank you so much for sorting that.

**Comment by FurquanAnwer** [comment]
**It's not working. I run the following code. -** 
var cloud_masks = require('users/fitoprincipe/geetools:cloud_masks');
var landsatSRfunction = cloud_masks.landsatSR2;
var L8Image = ee.Image('LANDSAT/LC08/C02/T1_L2/LC08_140046_20200115');//collection 2
var masked_image = landsatSRfunction()(L8Image);
var vis = {bands:['SR_B4', 'SR_B3', 'SR_B2'], min:0, max:30000}
Map.addLayer(masked_image, vis, 'Landsat 8 SR masked');
Map.centerObject(masked_image)

**Following error comes -** 
In users/fitoprincipe/geetools:cloud_masks
Line 113: cmask is not defined

**Comment by fitoprincipe** [comment]
Yes, I am sorry, I left a "test" code.. try it now: https://code.earthengine.google.com/f7e2dd98dd75f5f968ecd16e0ebd0940

**Comment by FurquanAnwer** [comment]
Yes, It is working .
Thanks a lot , sir.
